pool:
  name: Azure Pipelines

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: |
   python3 -V 
   python3 -m venv .venv
   source .venv/bin/activate
   python3 -m pip install --upgrade pip
   pip install -r requirements.in

  workingDirectory: project
  displayName: 'Install requirements'

- script: |
   source .venv/bin/activate
   python3 -m pip install pytest
   pytest

  workingDirectory: project
  displayName: 'Run pytest'

- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'docker hub connection'
    repository: 'paulbhs/website-portfolio'
    Dockerfile: project/Dockerfile
    buildContext: project

- script: |
    git push --prune https://github.com/Pyodin/website-portfolio.git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
  condition: eq(variables['Build.SourceBranch'], 'main')